service: test-nestjs
frameworkVersion: ~4.19.1

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-northeast-1
  stage: dev

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['@types/*', '*.test.*', '*.spec.*']
    external: ['class-validator', 'class-transformer', '@nestjs/websockets', '@nestjs/microservices', '@nestjs/websockets/socket-module', '@nestjs/microservices/microservices-module']
    target: node22
    define:
      'require.main': undefined
    platform: node

package:
  individually: true
  exclude:
    - src/**
    - test/**
    - .git/**
    - .vscode/**
    - README.md
    - pnpm-lock.yaml
    - yarn.lock
    - package.json
    - tsconfig*.json
    - nest-cli.json
    - .prettierrc
    - .eslintrc.js
    - Procfile
    - node_modules/**
  include:
    - 'node_modules/@nestjs/**/*'
    - 'node_modules/@vendia/**/*'
    - 'node_modules/@codegenie/**/*'
    - 'node_modules/aws-lambda/**/*'
    - 'node_modules/reflect-metadata/**/*'
    - 'node_modules/rxjs/**/*'
